### ISSUE TITLE
Cli_test.go Test skevt

### ISSUE THREAD

**Issue by OskarHavo** [OskarHavo/D7024E-Labb#20]
PUT
 
Den känner inte igen att inputen PRECIS har lagts in redan. Den returnar hashen istället för "already exists".
Det har nog med nästa problem att göra..

![put](https://user-images.githubusercontent.com/32604330/135663996-e01ea038-073a-4c49-8d85-6163ef9afff2.PNG)

GET
Här vi ser vi att det funkar med get på VALID input, alltså något som redan finns.
Men sen när man provar något som inte finns så säger den att längden på storage(?) är 0. Alltså tom.
Det är som att den resettar sig på något väldigt skevt sätt (har med async att göra?).

![get](https://user-images.githubusercontent.com/32604330/135663999-b1050486-94cf-4a4d-8fee-b66896b51fd1.PNG)

**Comment by robdan7** [comment]
I cli_test.go rad 197:
```
inputHash := "loremipsum"
_, output_2_2 := get(inputHash, &net)
```

Funktionen `get` tar in ett hashvärde i **hexformat**, inte en vanlig sträng. Byt ut texten mot t.ex. 20 nollor ungefär som i _**routingtable_test.go**_. Det står i felmeddelandet att KademliaID inte kan skapa ett ID. Det är alltså inte Kademlia som tappar bort din data.
